version: '3.1'

services:

  app-serve:
    build: .
    image: myapp
    command: npm run serve:sw
    expose:
     - 4200

  app-e2e-tests:
    image: myapp
    command: dockerize -wait tcp://app-serve:4200 -wait tcp://selenium-chrome-standalone:4444 -timeout 10s -wait-retry-interval 1s bash -c "npm run e2e:docker"
    depends_on:
      - app-serve
      - selenium-chrome-standalone

  selenium-chrome-standalone:
    expose:
     - 44444
    image: selenium/standalone-chrome
